
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        property_image:
            uri_prefix: /images/elghazzali
            upload_destination: '%kernel.project_dir%/public/images/elghazzali'
            namer: Vich\UploaderBundle\Naming\UniqidNamer