vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        property_image:
            uri_prefix: '%app.path.property_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.property_image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer